table 'Localized Labels'
	isHidden
	lineageTag: 9382e5cc-a24f-4732-a86b-8255ec745062

	measure 'My Report Title' = 0
		isHidden
		lineageTag: a0e4b6e8-cdcb-4d81-92a0-bf8e6f056737

	measure 'My Button Caption' = 0
		isHidden
		lineageTag: 3479de64-4079-43b6-9504-e3424deb6e3d

	measure 'My Visual Title' = 0
		isHidden
		lineageTag: f545aa68-feea-4deb-ba31-c9bb51b1e4bd

	measure 'Product sales report' = 0
		isHidden
		lineageTag: 3b510bc1-888b-4f16-bfd0-1745fa3fddfd

	measure ReportTitle = 0
		isHidden

	measure TotalCustomers = 0
		isHidden

	measure SalesAmount = 0
		isHidden

	measure NumberOfSales = 0
		isHidden

	measure ExplainationText = 0
		isHidden

	measure ProductsTableTitle = 0
		isHidden

	column unused
		isHidden
		displayFolder: unused
		lineageTag: 63f13424-767b-4a38-a071-191c96749442
		isNameInferred
		sourceColumn: [unused]

	partition Partition = calculated
		source = DATATABLE("unused", STRING, {{"This is a table automatically generated by Translations Builder"}})

