table 'Localized Labels'
	isHidden
	lineageTag: 9382e5cc-a24f-4732-a86b-8255ec745062

	measure 'My Report Title' = 0
		isHidden
		lineageTag: a0e4b6e8-cdcb-4d81-92a0-bf8e6f056737

	measure 'My Button Caption' = 0
		isHidden
		lineageTag: 3479de64-4079-43b6-9504-e3424deb6e3d

	measure 'My Visual Title' = 0
		isHidden
		lineageTag: f545aa68-feea-4deb-ba31-c9bb51b1e4bd

	measure 'Product sales report' = 0
		isHidden
		lineageTag: 3b510bc1-888b-4f16-bfd0-1745fa3fddfd

	measure ReportTitle = 0
		isHidden
		lineageTag: 0688694b-068b-4079-a29c-472e76aa3d29

	measure TotalCustomers = 0
		isHidden
		lineageTag: 8875e4b7-9e07-48ba-8323-ec97b052be7f

	measure SalesAmount = 0
		isHidden
		lineageTag: c2b2fdd2-56a1-4bcb-87ed-e9a3aa06d610

	measure NumberOfSales = 0
		isHidden
		lineageTag: e4b12fb6-4ec2-440a-8e4a-b5984aaa1311

	measure ExplainationText = 0
		isHidden
		lineageTag: aa58ccbf-753c-40d3-8a3a-349ce88be1df

	measure ProductsTableTitle = 0
		isHidden
		lineageTag: 2ef05e0b-ae39-45c6-9877-ec925e8b9a94

	column unused
		isHidden
		displayFolder: unused
		lineageTag: 63f13424-767b-4a38-a071-191c96749442
		summarizeBy: none
		isNameInferred
		sourceColumn: [unused]

		annotation SummarizationSetBy = Automatic

	partition Partition = calculated
		mode: import
		source = DATATABLE("unused", STRING, {{"This is a table automatically generated by Translations Builder"}})

