table 'Translated Localized Labels'

	measure 'My Report Title Label' = "My Report Title"

	measure 'My Button Caption Label' = "My Button Caption"

	measure 'My Visual Title Label' = "My Visual Title"

	measure 'Product sales report Label' = "Product sales report"

	measure 'ReportTitle Label' =
			SWITCH(USERCULTURE(),
			   "fr-FR", "Rapport annuel Adventure Works 2024",
			   "Adventure Works financial report 2024"
			)

	measure 'TotalCustomers Label' =
			SWITCH(USERCULTURE(),
			   "fr-FR", "Nombre de clients en 2025",
			   "Total customers in 2025"
			)

	measure 'SalesAmount Label' =
			SWITCH(USERCULTURE(),
			   "fr-FR", "Montant des ventes 2024",
			   "Sales amount for 2024"
			)

	measure 'NumberOfSales Label' =
			SWITCH(USERCULTURE(),
			   "fr-FR", "Nombre de ventes en 2024",
			   "Number of sales in 2024"
			)

	measure 'ExplainationText Label' = "This is a text that explains that 2024 wasn't the greatest year ever for Adventure Works but I want to re-assure our investors in the dedication of the team and new strategy for 2025"

	measure 'ProductsTableTitle Label' =
			SWITCH(USERCULTURE(),
			   "fr-FR", "Liste des produits 2024",
			   "Product list 2024"
			)

	column unused
		isHidden
		displayFolder: unused
		isNameInferred
		sourceColumn: [unused]

	partition Partition = calculated
		source = DATATABLE("unused", STRING, {{"This is a table automatically generated by Translations Builder"}})

